version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10 # the primary container, where your job's commands are run
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - 
            "5e:72:6c:02:6b:9c:19:d8:e7:a3:55:c0:fa:ac:a2:12"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build