version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10 # the primary container, where your job's commands are run
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f0:e6:54:1d:2d:83:70:33:46:98:01:fa:0a:bf:15:ec"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build